name: Ceph daily build and test on openEuler

on:
  schedule:
    - cron: '0 13 * * *'
  issue_comment:
    types: [created]

jobs:
  build-and-test:
    name: Build and test ceph from source
    if: ${{ contains(github.event.comment.body, 'recheck') || github.event_name == 'schedule' }}
    runs-on: arm64-32u-64g
    steps:
      - name: Echo environment information
        run: |
          /home/action/get_env_info.sh
      - name: Build ceph from source
        run: |
          pushd /home/action/ceph
          git pull
          git submodule update --init --recursive
          rm -rf build
          mkdir build
          pushd build
          cmake3 -DWITH_PYTHON3=3 -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DWITH_MGR_DASHBOARD_FRONTEND:BOOL=OFF -DWITH_TESTS=ON ..
          make -j32
          popd
          popd
      - name: Run unit test
        continue-on-error: true
        run: |
          pushd /home/action/ceph/build
          # unittest_mempool always fail, it should be fixed in ceph upstream
          make check -j32
          popd
      - name: Build RPM package
        run: |
          rm -rf /home/action/rpmbuild

          pushd /home/action/ceph
          git am ../0001-Add-openEuler-support-for-rpm-spec.patch
          ./make-dist
          rpmdev-setuptree
          mv ceph-1* ~/rpmbuild/SOURCES
          tar --strip-components=1 -C ~/rpmbuild/SPECS/ --no-anchored -xvjf ~/rpmbuild/SOURCES/ceph-1* "ceph.spec"
          popd

          pushd /home/action/rpmbuild
          rpmbuild -ba SPECS/ceph.spec
          popd

          pushd /home/action/ceph
          git reset --hard HEAD^
          popd
      - name: Save RPM package
        run: |
          pushd /home/action/package
          mkdir $(date +"%Y-%m-%d")
          cp -r /home/action/rpmbuild/RPMS $(date +"%Y-%m-%d")
          popd
