name: Ceph daily build and test on openEuler

on:
  schedule:
    - cron: '0 13 * * *'
  issue_comment:
    types: [created]

jobs:
  build-and-test:
    name: Build and test ceph from source
    if: ${{ contains(github.event.comment.body, 'recheck') || github.event_name == 'schedule' }}
    runs-on: arm64-32u-64g
    steps:
      - name: Echo environment information
        run: |
          /opt/code/action/get_env_info.sh
      - name: Build ceph from source
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY:/usr/local/lib64:/usr/local/lib/
          pushd /opt/code/ceph
          git pull
          rm -rf build
          mkdir build
          pushd build
          cmake3 -DWITH_PYTHON3=3 -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DWITH_MGR_DASHBOARD_FRONTEND:BOOL=OFF -DWITH_TESTS=ON ..
          make -j32
          popd
          popd
      - name: Run unit test
        continue-on-error: true
        run: |
          pushd /opt/code/ceph/build
          # unittest_mempool always fail, it should be fixed in ceph upstream
          make check -j32
          popd
